### ISSUE TITLE
Parse error: syntax error, unexpected ')', expecting ']' in view.php on line 168

### ISSUE THREAD

**Issue by Hajmer777** [leszcz/amxbans-php7#1]
view.php

Parse error: syntax error, unexpected ')', expecting ']' in view.php on line 168

  $last_ban_arr    = [
    "steamid"  => $steamid,
    "nickname"  => htmlspecialchars(_substr($lb->player_nick, 15)),
    "reason"  => htmlspecialchars(_substr($lb->ban_reason, 15)),
    "created"  => $lb->ban_created,
    "length"  => $ban_length,
(168)    "time"    => time());
  ];

**Comment by leszcz** [comment]
Fixed :) 
Please check.

**Comment by Hajmer777** [comment]
hello again (sveikas vel)
tnx for job :)
again error
Parse error: syntax error, unexpected end of file in /csbans/view.php on line 232

**Comment by leszcz** [comment]
Fixed, check pls.

**Comment by Hajmer777** [comment]
check :)

Warning: Use of undefined constant total - assumed 'total' (this will throw an Error in a future version of PHP) in view.php on line 138

Warning: Use of undefined constant permanent - assumed 'permanent' (this will throw an Error in a future version of PHP) in view.php on line 139

Warning: Use of undefined constant active - assumed 'active' (this will throw an Error in a future version of PHP) in view.php on line 140

Warning: Use of undefined constant temp - assumed 'temp' (this will throw an Error in a future version of PHP) in view.php on line 141

Warning: Use of undefined constant active - assumed 'active' (this will throw an Error in a future version of PHP) in view.php on line 141

Warning: Use of undefined constant permanent - assumed 'permanent' (this will throw an Error in a future version of PHP) in view.php on line 141

Warning: Use of undefined constant admins - assumed 'admins' (this will throw an Error in a future version of PHP) in view.php on line 142

Warning: Use of undefined constant servers - assumed 'servers' (this will throw an Error in a future version of PHP) in view.php on line 143

**Comment by leszcz** [comment]
That's error was generated by original author but I'll fixed it now. Thanks! :)
