### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by kelleboyy** [leszcz/amxbans-php7#2]
setup.php not working

**Comment by leszcz** [comment]
Hi @kelleboyy, can you paste here error logs from webserver without absolute paths and domain?

**Comment by kelleboyy** [comment]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported functions.inc line 42

**Comment by leszcz** [comment]
Hi, how version PHP you have?

czw., 21 gru 2023, 15:33 użytkownik kelleboyy ***@***.***>
napisał:

**Comment by kelleboyy** [comment]
My php version is 8.2.12

**Comment by leszcz** [comment]
Thanks, i will fix after Christmas.
Merry Christmas

sob., 23 gru 2023, 18:13 użytkownik kelleboyy ***@***.***>
napisał:

**Comment by kelleboyy** [comment]
Were you able to fix it?

**Comment by leszcz** [comment]
Good morning friend, i want to fix it today.

**Comment by kelleboyy** [comment]
How is it going?

**Comment by leszcz** [comment]
I'm working on it, too much problems

pon., 8 sty 2024, 19:51 użytkownik kelleboyy ***@***.***>
napisał:

**Comment by leszcz** [comment]
Sorry for the lack of response, but I'm still working on the code.
There is a problem with modifying the installer, specifically with loading the template for installation.

**Comment by leszcz** [comment]
@kelleboyy Can you check now?

**Comment by NiceFeatures** [comment]
@leszcz still not working

[22-Feb-2024 02:07:49 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; dynamicPage has a deprecated constructor in /home/mysite/public_html/webpanel/setup.php on line 67
[22-Feb-2024 02:07:49 UTC] PHP Fatal error:  Uncaught  --> Smarty: dynamicPage->clear_compiled_tpl() undefined method <-- 
  thrown in /home/mysite/public_html/webpanel/include/smarty/sysplugins/smarty_internal_undefined.php on line 47

**Comment by leszcz** [comment]
Hi @NiceFeatures - i've repaired setup and make some improvements in new commit. :)

**Comment by D4NTE98** [comment]
Hello, i have the same problem on newest pack
